
const products = [
    {
        _id: '1',
        name: 'Tomato',
        image: '/Images/ProductImages/tomato.jpg',
        description: 'anything temp',
        store: 'Netto',
        category: 'Vegetables',
        price: 2.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '2',
        name: 'Tomato',
        image: '/Images/ProductImages/tomato1.jpg',
        description: 'anything temp',
        store: 'Lidl',
        category: 'Vegetables',
        price: 1.99,
        countInStock: 10,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '3',
        name: 'Tomato',
        image: '/Images/ProductImages/tomato2.jpg',
        description: 'anything temp',
        store: 'Aldi',
        category: 'Vegetables',
        price: 3.99,
        countInStock: 40,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '4',
        name: 'Onion',
        image: '/Images/ProductImages/onion.jpg',
        description: 'anything temp',
        store: 'Netto',
        category: 'Vegetables',
        price: 4.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '5',
        name: 'Onion',
        image: '/Images/ProductImages/onion1.jpg',
        description: 'anything temp',
        store: 'Lidl',
        category: 'Vegetables',
        price: 6.99,
        countInStock: 30,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '6',
        name: 'Onion',
        image: '/Images/ProductImages/onion2.jpg',
        description: 'anything temp',
        store: 'Kaufland',
        category: 'Vegetables',
        price: 2.99,
        countInStock: 80,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '7',
        name: 'Banana',
        image: '/Images/ProductImages/banana.jpg',
        description: 'anything temp',
        store: 'Aldi',
        category: 'Fruits',
        price: 1.99,
        countInStock: 250,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '8',
        name: 'Cucumber',
        image: '/Images/ProductImages/cucumber.jpg',
        description: 'anything temp',
        store: 'Penny',
        category: 'Vegetables',
        price: 3.99,
        countInStock: 40,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '9',
        name: 'Cucumber',
        image: '/Images/ProductImages/cucumber1.jpg',
        description: 'anything temp',
        store: 'Netto',
        category: 'Vegetables',
        price: 4.99,
        countInStock: 9,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '10',
        name: 'Banana',
        image: '/Images/ProductImages/banana1.jpg',
        description: 'anything temp',
        store: 'Lidl',
        category: 'Fruits',
        price: 1.59,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '11',
        name: 'Banana',
        image: '/Images/ProductImages/banana2.jpg',
        description: 'anything temp',
        store: 'Netto',
        category: 'Fruits',
        price: 1.00,
        countInStock: 20,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '12',
        name: 'Apple',
        image: '/Images/ProductImages/apple.jpg',
        description: 'anything temp',
        store: 'Penny',
        category: 'Fruits',
        price: 11.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '13',
        name: 'Apple',
        image: '/Images/ProductImages/apple1.jpg',
        description: 'anything temp',
        store: 'Aldi',
        category: 'Fruits',
        price: 4.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '14',
        name: 'Apple',
        image: '/Images/ProductImages/apple2.jpg',
        description: 'anything temp',
        store: 'Netto',
        category: 'Fruits',
        price: 1.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '15',
        name: 'Cucumber',
        image: '/Images/ProductImages/cucumber2.jpg',
        description: 'anything temp',
        store: 'Penny',
        category: 'Vegetables',
        price: 19.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '16',
        name: 'Orange',
        image: '/Images/ProductImages/orange.jpg',
        description: 'anything temp',
        store: 'Netto',
        category: 'Fruits',
        price: 15.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '17',
        name: 'Orange',
        image: '/Images/ProductImages/orange1.jpg',
        description: 'anything temp',
        store: 'Aldi',
        category: 'Fruits',
        price: 12.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '18',
        name: 'Orange',
        image: '/Images/ProductImages/orange2.jpg',
        description: 'anything temp',
        store: 'Lidl',
        category: 'Fruits',
        price: 13.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '19',
        name: 'Chicken',
        image: '/Images/ProductImages/chicken.jpg',
        description: 'anything temp',
        store: 'Lidl',
        category: 'Meet',
        price: 21.00,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '20',
        name: 'Chicken',
        image: '/Images/ProductImages/chicken1.jpg',
        description: 'anything temp',
        store: 'Netto',
        category: 'Meet',
        price: 21.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '21',
        name: 'Chicken',
        image: '/Images/ProductImages/chicken2.jpg',
        description: 'anything temp',
        store: 'Aldi',
        category: 'Meet',
        price: 23.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '22',
        name: 'Mutton',
        image: '/Images/ProductImages/mutton.jpg',
        description: 'anything temp',
        store: 'Netto',
        category: 'Meet',
        price: 51.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '23',
        name: 'Mutton',
        image: '/Images/ProductImages/mutton1.jpg',
        description: 'anything temp',
        store: 'Lidl',
        category: 'Meet',
        price: 31.99,
        countInStock: 250,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '24',
        name: 'Mutton',
        image: '/Images/ProductImages/mutton2.jpg',
        description: 'anything temp',
        store: 'Penny',
        category: 'Meet',
        price: 21.99,
        countInStock: 90,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '25',
        name: 'Beans',
        image: '/Images/ProductImages/beans.jpg',
        description: 'anything temp',
        store: 'Penny',
        category: 'Organic',
        price: 11.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '26',
        name: 'Beans',
        image: '/Images/ProductImages/beans1.jpg',
        description: 'anything temp',
        store: 'Netto',
        category: 'Organic',
        price: 12.00,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '27',
        name: 'Beans',
        image: '/Images/ProductImages/beans2.jpg',
        description: 'anything temp',
        store: 'Aldi',
        category: 'Organic',
        price: 9.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '28',
        name: 'Capsicum',
        image: '/Images/ProductImages/capsicum.jpg',
        description: 'anything temp',
        store: 'Lidl',
        category: 'Organic',
        price: 7.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '29',
        name: 'Capsicum',
        image: '/Images/ProductImages/capsicum1.jpg',
        description: 'anything temp',
        store: 'Netto',
        category: 'Organic',
        price: 5.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
    {
        _id: '30',
        name: 'Capsicum',
        image: '/Images/ProductImages/capsicum2.jpg',
        description: 'anything temp',
        store: 'Aldi',
        category: 'Organic',
        price: 2.99,
        countInStock: 50,
        rating: 4.5,
        reviewsNum: 4
    },
]

module.exports = products